<<<<<<< HEAD
lannguage: ruby
=======
---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
>>>>>>> ca49b9130a6dd79e10b86e7edb33316914c82b71
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
<<<<<<< HEAD
before_install: rm Gemfile.lock || true
script:
 - "gem list"
 - "bundle exec rake lint"
 - "bundle exec rake syntax"
 - "bundle exec rake spec"
=======
  - 2.1.0
script: bundle exec rake test
>>>>>>> ca49b9130a6dd79e10b86e7edb33316914c82b71
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
<<<<<<< HEAD
matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.0.0
=======
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
matrix:
  exclude:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 2.7.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.1.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.2.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.3.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 3.4.0"
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 2.0.0
    env: PUPPET_VERSION="~> 4.0.0"
  - rvm: 2.1.0
    env: PUPPET_VERSION="~> 4.0.0"
>>>>>>> ca49b9130a6dd79e10b86e7edb33316914c82b71
